# Generated by Django 4.1.7 on 2023-02-18 17:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('9d8bb85b-dfa2-4a9e-b943-41e57dcb8efb'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('objectives', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('77257ea4-44db-4ce9-8b70-852af2a416fb'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('grade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lpsaccommodation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('45e3b7fc-0454-46c7-b79f-b54e3755de84'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('accommodation', models.TextField()),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.lessonplan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='IEP',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('a2181acb-e069-4f7d-98f5-53b82a00740b'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('accommodation', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
            ],
        ),
    ]
