# Generated by Django 4.1.7 on 2023-02-18 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iep',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('867a1d36-f84c-441c-a287-33715502391b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d5a98bcd-4d6c-4b61-9f52-cef8ed7a91cc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lpsaccommodation',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('866481c2-1b8c-47ca-b7fe-9adf725e7a9a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e4ba79d1-60c7-4298-b68b-60f42a848b88'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
