# Generated by Django 4.1.7 on 2023-02-18 18:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_iep_uuid_alter_lessonplan_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iep',
            old_name='accommodation',
            new_name='accommodation',
        ),
        migrations.RenameField(
            model_name='lpsaccommodation',
            old_name='accommodation',
            new_name='accommodation',
        ),
        migrations.AlterField(
            model_name='iep',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b44441e4-8d03-4672-b718-feadf5464d68'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('08150565-a4d1-4e8e-ace2-bf73bda44b76'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lpsaccommodation',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1fa86334-2356-4acc-bcac-2d9d7c879605'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ec886bb6-4fe3-4619-b465-1fd5d3e1bd11'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
