# Generated by Django 4.1.7 on 2023-02-18 18:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_accomodation_iep_accommodation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iep',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('818ee3dc-83e4-48fd-ad5c-1dcc22e20263'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a0a11229-26ac-4757-8d64-fb020d4ec251'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lpsaccommodation',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('37d677aa-d3eb-4eb1-8e10-462766e7478c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c9a2bed9-1996-44c3-81bb-560475d0c9b7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
