# Generated by Django 4.1.7 on 2023-02-18 18:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_iep_uuid_alter_lessonplan_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iep',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5dd87384-b706-4e17-a7f2-20f17dad7797'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3b6252ae-7fe2-4e23-9f9b-2161919992a9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lpsaccommodation',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('deb40b95-c1bb-48a8-84d7-54b890002d5e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e74ed072-0721-493c-8f25-e7c756972715'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
