# Generated by Django 4.1.7 on 2023-02-18 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_iep_uuid_alter_lessonplan_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iep',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.student'),
        ),
    ]
