# Generated by Django 4.1.7 on 2023-02-19 01:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_iep_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='present_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
