# Generated by Django 4.1.7 on 2023-02-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_grade_student_standard_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='disability',
            field=models.CharField(choices=[('ADHD', 'ADHD'), ('Hearing', 'Hearing'), ('ASD', 'ASD'), ('Learning Disability', 'Learning Disability')], default='None', max_length=255),
        ),
    ]
