# Generated by Django 4.1.7 on 2023-02-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_student_disability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='disability',
            field=models.CharField(choices=[('ADHD', 'ADHD'), ('Hearing', 'Hearing'), ('ASD', 'ASD'), ('Learning Disability', 'Learning Disability'), ('None', 'None')], max_length=255),
        ),
    ]
