# Generated by Django 4.1.7 on 2023-02-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_student_disability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='disability',
            field=models.CharField(max_length=255),
        ),
    ]
