# Generated by Django 4.1.7 on 2023-02-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_student_disability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.CharField(choices=[('Math', 'Math'), ('Reading & Writing', 'Reading & Writing')], max_length=50),
        ),
    ]
